import { PERMISSIONS, type KnownPermission, type RoleCode } from './permissions.js';

const all = PERMISSIONS;

function pick(...codes: KnownPermission[]): KnownPermission[] {
  return codes;
}

export const ROLE_PERMISSIONS: Record<RoleCode, readonly KnownPermission[]> = {
  employee: pick(
    'employee.read:self',
    'employee.update:self',
    'employee.field.payroll.read:self',
    'employee.field.identity.read:self',
    'employee.field.contact.read:self',
    'org.structure.read:company',
    'leave.request.create:self',
    'leave.request.read:self',
    'leave.request.withdraw:self',
    'leave.balance.read:self',
    'leave.policy.read:company',
    'holiday.calendar.read:company',
    'team.availability.read:team',
    'attachment.upload:self',
    'attachment.read:self',
    'attachment.medical.read:self',
    'attendance.read:self',
    'notification.read:self',
    'user.account.read:self',
    'user.session.revoke:self',
  ),
  manager: pick(
    'employee.read:self',
    'employee.read:reports_recursive',
    'employee.update:self',
    'employee.field.payroll.read:self',
    'employee.field.identity.read:self',
    'employee.field.contact.read:self',
    'employee.field.contact.read:direct_reports',
    'org.structure.read:company',
    'leave.request.create:self',
    'leave.request.read:self',
    'leave.request.read:reports_recursive',
    'leave.request.withdraw:self',
    'leave.balance.read:self',
    'leave.balance.read:direct_reports',
    'leave.policy.read:company',
    'holiday.calendar.read:company',
    'team.availability.read:reports_recursive',
    'attachment.upload:self',
    'attachment.read:self',
    'attachment.read:direct_reports',
    'attachment.medical.read:self',
    'attendance.read:self',
    'attendance.read:direct_reports',
    'attendance.correct:direct_reports',
    'report.leave.view:reports_recursive',
    'report.export:reports_recursive',
    'notification.read:self',
    'user.account.read:self',
    'user.session.revoke:self',
  ),
  hr_officer: pick(
    'employee.read:company',
    'employee.create:company',
    'employee.update:company',
    'employee.archive:company',
    'employee.field.identity.read:company',
    'employee.field.contact.read:company',
    'org.structure.read:company',
    'org.structure.manage:company',
    'leave.request.create:self',
    'leave.request.create:company',
    'leave.request.read:company',
    'leave.request.approve:company',
    'leave.request.reject:company',
    'leave.request.withdraw:self',
    'leave.request.cancel:company',
    'leave.balance.read:company',
    'leave.balance.adjust:company',
    'leave.policy.read:company',
    'leave.policy.manage:company',
    'holiday.calendar.read:company',
    'holiday.calendar.manage:company',
    'approval.workflow.manage:company',
    'team.availability.read:company',
    'attachment.upload:company',
    'attachment.read:company',
    'attachment.medical.read:company',
    'attendance.import:company',
    'attendance.read:company',
    'attendance.correct:company',
    'report.leave.view:company',
    'report.export:company',
    'notification.read:self',
    'audit.read:company',
    'user.account.read:company',
    'import.run:company',
  ),
  payroll_officer: pick(
    'employee.read:company',
    'employee.field.payroll.read:company',
    'employee.field.payroll.update:company',
    'org.structure.read:company',
    'leave.request.create:self',
    'leave.request.read:self',
    'leave.request.withdraw:self',
    'leave.balance.read:company',
    'leave.policy.read:company',
    'holiday.calendar.read:company',
    'attendance.read:company',
    'report.leave.view:company',
    'report.export:company',
    'payroll.export:company',
    'notification.read:self',
    'user.account.read:self',
    'user.session.revoke:self',
  ),
  admin: all.filter(
    (p) =>
      !p.startsWith('employee.field.payroll') &&
      !p.startsWith('payroll.export') &&
      p !== 'leave.balance.adjust:company',
  ),
  auditor: pick(
    'employee.read:company',
    'employee.field.payroll.read:company',
    'employee.field.identity.read:company',
    'employee.field.contact.read:company',
    'org.structure.read:company',
    'leave.request.read:company',
    'leave.balance.read:company',
    'leave.policy.read:company',
    'holiday.calendar.read:company',
    'team.availability.read:company',
    'attachment.read:company',
    'attachment.medical.read:company',
    'attendance.read:company',
    'report.leave.view:company',
    'report.export:company',
    'payroll.export:company',
    'notification.read:self',
    'audit.read:company',
    'user.account.read:company',
    'system.health.read:company',
    'system.logs.read:company',
  ),
};

export const SYSTEM_ROLES: { code: RoleCode; name: string }[] = [
  { code: 'employee', name: 'Employee' },
  { code: 'manager', name: 'Manager' },
  { code: 'hr_officer', name: 'HR Officer' },
  { code: 'payroll_officer', name: 'Payroll Officer' },
  { code: 'admin', name: 'System Administrator' },
  { code: 'auditor', name: 'Read-only Auditor' },
];
